bin/testTableEntry: testTableEntry.cpp TableEntry.h
	mkdir -p bin
	g++ -std=c++17 -o bin/testTableEntry testTableEntry.cpp
1 bin/testHashTable: testHashTable.cpp HashTable.h
	mkdir -p bin
	g++ -std=c++17 -o bin/testHashTable testHashTable.cpp
clean:
	rm -rf *.o *.gch bin
